 @startuml
title Cancer data evolution – Diagnosis + First Treatment (Date 0 - 4)

skinparam class {
  BackgroundColor White
}

scale 0.8

' ===========================================
' DATE 0 – initial capture (conceptual record)
' ===========================================
package "Date 0 (2018-05-01)\nCancer Condition Diagnosis" {
  class CancerPatient1 <<fixed>> {
    demographics
    comorbiditiesAtDiagnosis
  }
  
  class CancerConditionAtDiagnosis1 <<fixed>> {
    tumourGrade = XXX
    histologyBehaviour = XXX
    bodySite = XXX
    visitDate 
    biopsyDate 
    labReportDate[biomarker] 
    ImagingDate = 2018-05-01 'Date 0
  }

  class CancerStage1 <<fixed>> {
    type = Clinical
    classificationType = TNM
    value = T2,N0,M0
  }

  class Imaging1 <<fixed>> {
    type = MRI
    bodySite = XXX
  }
 
}

' Links inside Date 0
CancerPatient1 --> CancerConditionAtDiagnosis1 : is affected by
CancerConditionAtDiagnosis1 --> CancerStage1 : has a
CancerStage1 --> Imaging1 : defined throught a

package "Cancer Treatment 1" {

' ===========================================
' Radiotherapy
' ===========================================
'package "Radiotherapy" {
    ' ===========================================
  ' DATE 2 – 2018-10-12 - DATE 3 2018-09-10 (radiotherapy)
  ' ===========================================
  package "Date 2 (2018-09-10) - Date 3 (2018-10-12)\nRadiotherapy" {
    class Radiotherapy1 {
      intent = Definitive
      bodySite = XXX
      settings = Postoperative/Adjuvant
      startDate = 2018-09-10   'Date 2
      endDate   = 2018-10-12   'Date 3
    }
}
/'   ' ===========================================
' DATE 2 – 2018-09-10 (radiotherapy)
' ===========================================
  package "Date 2 (2018-09-10)\nRadiotherapy start" {
    class Radiotherapy {
      intent = definitive
      target_site = ...
      start_date = 2018-09-10   ' Date 2
      end_date   = 2018-10-12   ' Date 3
    }
  } '/

'}

' ===========================================
' DATE 1 – 2018-06-12 (procedure / surgery)
' ===========================================
package "Date 1 (2018-06-12)\nSurgery" {
  class Surgery1 {
    intent = Definitive
    bodySite = XXX
    date = 2018-06-12 'Date 1
  }
  class CancerStage2 <<fixed>> {
    type = Pathological
    classificationType = TNM
    value = T2,N1,M0
  }

}


CancerConditionAtDiagnosis1 --> Surgery1 : is the target of
'CancerStage2 --> Surgery1 : defined throught a
Surgery1 <-- CancerStage2 : defined throught a
CancerConditionAtDiagnosis1 --> CancerStage2 : can have a
CancerConditionAtDiagnosis1 --> Radiotherapy1 : is the target of
Surgery1 -[hidden]-> Radiotherapy1
CancerPatient1 --> Surgery1 : is the subject of
CancerPatient1 --> Radiotherapy1 : is the subject of
} 

@enduml